services:
  api: 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    networks:
      - home-library-service
    depends_on:
      - postgres
    restart: always
  postgres:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - /var/lib/postgresql/data
    networks:
      - home-library-service
    restart: always
volumes:
  api:
  postgres:
networks:
  home-library-service:
    driver: bridge
